spring:
  jackson:
    default-property-inclusion: NON_NULL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#    接続方法
#      Driver Class: org.h2.Driver
#      JDBC URL: jdbc:h2:mem:testdb
#      User Name: sa
#      Password: (空白)

server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLSv1.2
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
